#pragma once

// Generated by Gemini

#ifdef __cplusplus

#define ENUM_FLAG_TYPE(name) name
#define BEGIN_ENUM_FLAG(name) enum class name : uint {
#define END_ENUM_FLAG(name) };
#define ENABLE_UINT_ENUM_BITWISE_OPERATORS(EnumType)                            \
                                                                                \
/* 1. Bitwise OR (|) */                                                         \
inline EnumType operator|(EnumType lhs, EnumType rhs) { return (EnumType)((uint)lhs | (uint)rhs); } \
                                                                               \
/* 2. Bitwise AND (&) */                                                       \
inline EnumType operator&(EnumType lhs, EnumType rhs) { return (EnumType)((uint)lhs & (uint)rhs); } \
                                                                               \
/* 3. Bitwise XOR (^) */                                                       \
inline EnumType operator^(EnumType lhs, EnumType rhs) { return (EnumType)((uint)lhs ^ (uint)rhs); } \
                                                                               \
/* 4. Bitwise NOT (~) */                                                       \
inline EnumType operator~(EnumType val) { return (EnumType)(~(uint)val); }      \
                                                                               \
/* 5. Compound OR assignment (|=) */                                           \
inline EnumType& operator|=(EnumType& lhs, EnumType rhs) { lhs = lhs | rhs; return lhs; } \
                                                                               \
/* 6. Compound AND assignment (&=) */                                          \
inline EnumType& operator&=(EnumType& lhs, EnumType rhs) { lhs = lhs & rhs; return lhs; } \
                                                                               \
/* 7. Compound XOR assignment (^=) */                                          \
inline EnumType& operator^=(EnumType& lhs, EnumType rhs) { lhs = lhs ^ rhs; return lhs; }

#else

#define ENUM_FLAG_TYPE(name) uint
#define BEGIN_ENUM_FLAG(name) struct name { uint use_ENUM_FLAG_TYPE_in_shader[65536]; enum {
#define END_ENUM_FLAG(name) }; };
#define ENABLE_UINT_ENUM_BITWISE_OPERATORS(EnumType)

#endif // __cplusplus
