<Project>
  <ItemGroup Condition="'$(MSBuildProjectExtension)' == '.vcxproj'">
    <ProjectCapability Include="PackageReferences" />
  </ItemGroup>

  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.vcxproj'">
    <NuGetTargetMoniker Condition="'$(NuGetTargetMoniker)' == ''">native,Version=v0.0</NuGetTargetMoniker>
    <RuntimeIdentifiers Condition="'$(RuntimeIdentifiers)' == ''">win;win-x86;win-x64;win-arm;win-arm64</RuntimeIdentifiers>
    <RestoreProjectStyle Condition="'$(RestoreProjectStyle)' == ''">PackageReference</RestoreProjectStyle>
  </PropertyGroup>

</Project>
